general {
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    lock_cmd = pidof hyprlock || hyprlock
}



listener {
    event = lid_switch
    on-close = hyprlock
    on-open = hyprctl dispatch dpms on
}
